"""YouTube video metadata models.

This module provides Pydantic models for YouTube video data including
individual video information and aggregated video data per track.
"""

# Standard library
from typing import Annotated

# Third-party
from pydantic import ConfigDict, Field

# Local
from msc.models.base import MSCBaseModel
from msc.models.track import SongstatsIdentifiers


class YouTubeVideo(MSCBaseModel):
    """YouTube video metadata.

    Represents a single YouTube video with its ID, view count, and
    channel information.

    Attributes:
        video_id: YouTube video ID (11-character alphanumeric).
        views: Total view count.
        channel_name: YouTube channel name that uploaded the video.

    Examples:
        >>> video = YouTubeVideo(
        ...     video_id="s0UcVIcQ8B4",
        ...     views=271568,
        ...     channel_name="Hardwell"
        ... )
        >>> video.video_id
        's0UcVIcQ8B4'
    """

    model_config = ConfigDict(frozen=True)  # Immutable

    video_id: Annotated[
        str,
        Field(
            alias="ytb_id",
            description="YouTube video ID"
        )
    ]
    views: Annotated[
        int,
        Field(
            ge=0,
            description="Total view count"
        )
    ]
    channel_name: Annotated[
        str,
        Field(description="YouTube channel name")
    ]

    @property
    def is_topic_channel(self) -> bool:
        """Check if video is from a topic channel.

        Topic channels are auto-generated by YouTube and typically
        end with " - Topic" (e.g., "Hardwell - Topic").

        Returns:
            True if channel name ends with " - Topic".

        Examples:
            >>> video = YouTubeVideo(
            ...     video_id="abc123",
            ...     views=1000,
            ...     channel_name="Hardwell - Topic"
            ... )
            >>> video.is_topic_channel
            True
        """
        return self.channel_name.endswith(" - Topic")


class YouTubeVideoData(MSCBaseModel):
    """Aggregated YouTube video data for a track.

    Contains all YouTube videos found for a track, including the most
    viewed video and all video IDs.

    Attributes:
        most_viewed: The most viewed video for this track.
        all_sources: List of all video IDs found for this track.
        songstats_identifiers: Songstats track identifiers.

    Examples:
        >>> video_data = YouTubeVideoData(
        ...     most_viewed=YouTubeVideo(
        ...         video_id="s0UcVIcQ8B4",
        ...         views=271568,
        ...         channel_name="Hardwell"
        ...     ),
        ...     all_sources=["s0UcVIcQ8B4", "ekZ06PHmxAw"],
        ...     songstats_identifiers=SongstatsIdentifiers(
        ...         songstats_id="qmr6e0bx",
        ...         songstats_title="16"
        ...     )
        ... )
        >>> video_data.most_viewed.views
        271568
    """

    model_config = ConfigDict(frozen=True)  # Immutable

    most_viewed: Annotated[
        YouTubeVideo,
        Field(description="Most viewed video for this track")
    ]
    all_sources: Annotated[
        list[str],
        Field(
            min_length=1,
            description="List of all video IDs found for this track"
        )
    ]
    songstats_identifiers: Annotated[
        SongstatsIdentifiers,
        Field(description="Songstats track identifiers")
    ]

    @property
    def video_count(self) -> int:
        """Total number of videos found.

        Returns:
            Number of videos in all_sources.

        Examples:
            >>> video_data.video_count
            2
        """
        return len(self.all_sources)
