"""Interactive demo for YouTube models.

This script demonstrates the YouTubeVideo and YouTubeVideoData models,
including topic channel detection and real data examples.

Requirements:
    - No external dependencies or setup required
    - Uses synthetic examples and real legacy data sample

Usage:
    python _demos/sandbox_youtube_models_demo.py
"""

# Standard library
import json

# Third-party
from pydantic import ValidationError

# Local
from msc.config.settings import PROJECT_ROOT
from msc.models.track import SongstatsIdentifiers
from msc.models.youtube import YouTubeVideo, YouTubeVideoData


def print_separator(title: str = "") -> None:
    """Print a formatted separator line.

    Args:
        title: Optional title to display in separator.
    """
    if title:
        print(f"\n{'=' * 80}")
        print(f" {title}")
        print(f"{'=' * 80}\n")
    else:
        print(f"{'=' * 80}\n")


def demo_youtube_video_creation() -> None:
    """Demonstrate YouTubeVideo creation."""
    print_separator("YouTubeVideo Creation")

    # Basic video
    print("Creating basic YouTubeVideo...")
    video = YouTubeVideo(
        video_id="s0UcVIcQ8B4",
        views=271568,
        channel_name="Hardwell"
    )
    print(f"✓ Video ID: {video.video_id}")
    print(f"  Views: {video.views:,}")
    print(f"  Channel: {video.channel_name}\n")

    # Using alias (ytb_id)
    print("Creating with alias 'ytb_id' (legacy format)...")
    video_aliased = YouTubeVideo(
        ytb_id="ekZ06PHmxAw",
        views=150000,
        channel_name="Revealed Recordings"
    )
    print(f"✓ video_id: {video_aliased.video_id}")
    print(f"  (Both 'video_id' and 'ytb_id' work)\\n")

    # View count validation
    print("Testing view count validation...")
    try:
        YouTubeVideo(
            video_id="abc123",
            views=-1000,
            channel_name="Test"
        )
    except ValidationError:
        print("✗ views=-1000 rejected (must be >= 0)\n")

    print("✓ YouTubeVideo creation working correctly\n")


def demo_topic_channel_detection() -> None:
    """Demonstrate topic channel detection."""
    print_separator("Topic Channel Detection")

    # Regular channel
    print("Regular channel (artist/label upload)...")
    regular_video = YouTubeVideo(
        video_id="s0UcVIcQ8B4",
        views=271568,
        channel_name="Hardwell"
    )
    print(f"  Channel: {regular_video.channel_name}")
    print(f"  is_topic_channel: {regular_video.is_topic_channel}\n")

    # Topic channel
    print("Topic channel (auto-generated by YouTube)...")
    topic_video = YouTubeVideo(
        video_id="abc123",
        views=500000,
        channel_name="Hardwell - Topic"
    )
    print(f"  Channel: {topic_video.channel_name}")
    print(f"  is_topic_channel: {topic_video.is_topic_channel}")
    print(f"  (Topic channels end with ' - Topic')\\n")

    # Comparison
    print("Comparison:")
    print(f"  'Hardwell': {regular_video.is_topic_channel}")
    print(f"  'Hardwell - Topic': {topic_video.is_topic_channel}")
    print(
        f"  'Revealed Recordings': {YouTubeVideo(video_id='x', views=0,
                                                 channel_name='Revealed Recordings').is_topic_channel}\n")

    print("✓ Topic channel detection working correctly\n")


def demo_youtube_video_data() -> None:
    """Demonstrate YouTubeVideoData model."""
    print_separator("YouTubeVideoData Model")

    # Create video data
    print("Creating YouTubeVideoData with most viewed video...")
    most_viewed = YouTubeVideo(
        video_id="s0UcVIcQ8B4",
        views=271568,
        channel_name="Hardwell"
    )
    identifiers = SongstatsIdentifiers(
        songstats_id="qmr6e0bx",
        songstats_title="16"
    )
    video_data = YouTubeVideoData(
        most_viewed=most_viewed,
        all_sources=["s0UcVIcQ8B4", "ekZ06PHmxAw", "cf7E_u0jATs"],
        songstats_identifiers=identifiers
    )

    print(f"✓ Most viewed video:")
    print(f"    ID: {video_data.most_viewed.video_id}")
    print(f"    Views: {video_data.most_viewed.views:,}")
    print(f"    Channel: {video_data.most_viewed.channel_name}\n")

    print(f"  All sources (video IDs):")
    for idx, video_id in enumerate(video_data.all_sources, 1):
        print(f"    {idx}. {video_id}")
    print()

    print(f"  Video count property: {video_data.video_count} videos")
    print(f"  Songstats ID: {video_data.songstats_identifiers.songstats_id}\n")

    # Validation: all_sources min_length
    print("Testing validation (all_sources must have at least 1 video)...")
    try:
        YouTubeVideoData(
            most_viewed=most_viewed,
            all_sources=[],
            songstats_identifiers=identifiers
        )
    except ValidationError:
        print("✗ all_sources=[] rejected (must have at least 1 video)\n")

    print("✓ YouTubeVideoData working correctly\n")


def demo_real_data_example() -> None:
    """Demonstrate with real legacy YouTube data."""
    print_separator("Real Legacy Data Example")

    legacy_file = PROJECT_ROOT / "_legacy/data/ytb_2024.json"

    if legacy_file.exists():
        print(f"Loading first item from {legacy_file}...")
        with open(legacy_file, encoding="utf-8") as f:
            legacy_data = json.load(f)

        first_item = legacy_data[0]

        # Extract components
        most_viewed_data = first_item["data"]["most_viewed"]
        all_sources = first_item["data"]["all_sources"]
        identifiers_data = first_item["songstats_identifiers"]

        # Create models
        most_viewed = YouTubeVideo(**most_viewed_data)
        identifiers = SongstatsIdentifiers(**identifiers_data)
        video_data = YouTubeVideoData(
            most_viewed=most_viewed,
            all_sources=all_sources,
            songstats_identifiers=identifiers
        )

        print(f"✓ Loaded YouTubeVideoData for track:")
        print(f"  Songstats ID: {video_data.songstats_identifiers.songstats_id}")
        print(f"  Songstats Title: {video_data.songstats_identifiers.songstats_title}\n")

        print(f"  Most viewed video:")
        print(f"    Video ID: {video_data.most_viewed.video_id}")
        print(f"    Views: {video_data.most_viewed.views:,}")
        print(f"    Channel: {video_data.most_viewed.channel_name}")
        print(f"    Topic channel: {video_data.most_viewed.is_topic_channel}\n")

        print(f"  Total videos found: {video_data.video_count}")
        print(f"  First 5 video IDs:")
        for idx, video_id in enumerate(video_data.all_sources[:5], 1):
            print(f"    {idx}. {video_id}")
        if video_data.video_count > 5:
            print(f"    ... and {video_data.video_count - 5} more\n")
        else:
            print()

    else:
        print(f"⚠ Legacy file not found: {legacy_file}")
        print("  (Skipping real data demo)\n")

    print("✓ Real data example completed\n")


def demo_json_serialization() -> None:
    """Demonstrate JSON serialization."""
    print_separator("JSON Serialization")

    # Create video data
    video = YouTubeVideo(
        video_id="s0UcVIcQ8B4",
        views=271568,
        channel_name="Hardwell"
    )
    identifiers = SongstatsIdentifiers(
        songstats_id="qmr6e0bx",
        songstats_title="16"
    )
    video_data = YouTubeVideoData(
        most_viewed=video,
        all_sources=["s0UcVIcQ8B4", "ekZ06PHmxAw"],
        songstats_identifiers=identifiers
    )

    # Serialize to JSON
    print("Serializing YouTubeVideoData to JSON...")
    json_str = video_data.model_dump_json(indent=2)
    print(json_str)
    print()

    # Deserialize from JSON
    print("Deserializing from JSON...")
    loaded_data = YouTubeVideoData.model_validate_json(json_str)
    print(f"✓ Loaded: {loaded_data.video_count} videos")
    print(f"  Most viewed: {loaded_data.most_viewed.views:,} views\n")

    print("✓ JSON serialization working correctly\n")


def demo_immutability() -> None:
    """Demonstrate model immutability."""
    print_separator("Model Immutability")

    video = YouTubeVideo(
        video_id="s0UcVIcQ8B4",
        views=271568,
        channel_name="Hardwell"
    )

    print("Attempting to modify frozen YouTubeVideo...")
    try:
        video.views = 500000
        print("✗ Modification succeeded (unexpected)")
    except ValidationError:
        print("✓ Modification rejected (model is frozen)")

    print("  Reason: ConfigDict(frozen=True) makes models immutable")
    print("  Benefits: Data integrity, thread safety, hashability\n")

    print("✓ Immutability working as expected\n")


def main() -> None:
    """Run all YouTube model demos."""
    print("=" * 80)
    print(" YouTubeVideo & YouTubeVideoData Models - Interactive Demo")
    print("=" * 80)

    demo_youtube_video_creation()
    demo_topic_channel_detection()
    demo_youtube_video_data()
    demo_real_data_example()
    demo_json_serialization()
    demo_immutability()

    print_separator()
    print("✓ All demos completed successfully!")
    print()


if __name__ == "__main__":
    main()
